FROM openjdk:8
ADD target/sample-order-management-app-1.0.0-SNAPSHOT.jar sample-order-management-app-1.0.0-SNAPSHOT.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "sample-order-management-app-1.0.0-SNAPSHOT.jar"]